---
title: "02_load"
format: html
---

```{r}
library(GEOquery)
```

# Load Data

```{r}
if (file.exists("../data/GSE45827_expression.csv")) {
  expr_data <- read.csv("../data/GSE45827_expression.csv", row.names = 1)
}
if (file.exists("../data/GSE45827_Phenotype_metadata.csv")) {
  pheno_data <- read.csv("../data/GSE45827_Phenotype_metadata.csv", row.names = 1)
}
if (file.exists("../data/GSE45827_Sample_metadata.csv")) {
  feature_data <- read.csv("../data/GSE45827_Sample_metadata.csv", row.names = 1)
}

```

```{r}
raw_file <- "../data/_raw/GSE45827.RData"
load(raw_file)
```

# Split Raw Data into 3 main Data Frames

-   Gene expression Data

-   Sample Metadata

-   Gene Metadata

```{r}
exprSet <- gse[[1]]

# Expression data
expr_data <- exprs(exprSet)

# Phenotype / sample metadata
pheno_data <- pData(exprSet)

# Feature (gene) metadata
feature_data <- fData(exprSet)
```

# Save Data Frames into csv files

```{r}
if (!file.exists("../data/GSE45827_expression.csv")) {
  write.csv(expr_data, "../data/GSE45827_expression.csv")
}
if (!file.exists("../data/GSE45827_Phenotype_metadata.csv")) {
  write.csv(pheno_data, "../data/GSE45827_Phenotype_metadata.csv")
}
if (!file.exists("../data/GSE45827_Sample_metadata.csv")) {
  write.csv(feature_data, "../data/GSE45827_Sample_metadata.csv")
}
```

```{r}
expr_data
```
