---
title: "pca_Natali_Alena"
format: html
---

# PCA Plot

### Load Libraries

```{r}
library(tidyverse)
library(ggbiplot)
library(devtools)

```

### Transpose data

```{r}
transp_expr <- t(expr_data)
```

```{r}
transp_expr <- data.frame(transp_expr)
```

### Adding columns for coloring

```{r}
transp_expr <- transp_expr |>
  mutate(cancer = pheno_data$`diagnosis:ch1`)
```

```{r}
transp_expr <- transp_expr |>
  mutate(subtype = pheno_data$`tumor subtype:ch1`)
```

### Removing empty values

```{r}
transp_expr <- transp_expr |>
  filter(!is.na(cancer))
```

```{r}
transp_expr <- transp_expr |>
  filter(!is.na(subtype))
```

### Adjusting non-cancer subtype values to Normal

```{r}
transp_expr <- transp_expr|>
  mutate(subtype = if_else(subtype == "N/A", "Normal", subtype))
```

### PCA Computation

```{r}
expr_only <- transp_expr |>  select(-subtype, -cancer)
```

```{r}
pc <- prcomp(expr_only, center = TRUE, scale. = TRUE)
```

```{r}
ggbiplot(pc, 
         obs.scale = 1,
         var.scale = 1,
         groups = transp_expr$cancer,
         var.axes = FALSE)
```

```{r}
ggbiplot(pc, 
         obs.scale = 1,
         var.scale = 1,
         groups = transp_expr$subtype,
         var.axes = FALSE)
  
```
